# Generated by Django 3.2.8 on 2021-10-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=510, null=True)),
                ('message', models.CharField(max_length=510)),
                ('exchange', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255)),
                ('interval', models.CharField(max_length=255)),
                ('bullish', models.BooleanField(default=False)),
                ('bearish', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='', max_length=510, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
